const list = [
  {
    id: 1,
    title: "The Eminem Show",
    author: "by Wonder House Books | 25 April 2018",
    price: 89,
    img: "https://upload.wikimedia.org/wikipedia/en/3/35/The_Eminem_Show.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Music to Be Murdered By",
    author: "by Maple Press  | 1 September 2020",
    price: 98,
    img: "https://upload.wikimedia.org/wikipedia/en/8/80/Eminem_-_Music_to_Be_Murdered_By.png",
    amount: 1,
  },
  {
    id: 3,
    title: "Encore",
    author: "by Om Books Editorial Team  | 25 November 2018",
    price: 143,
    img: "https://upload.wikimedia.org/wikipedia/en/b/b4/Encore_%28Eminem_album%29_coverart.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Lose Yourself",
    author: "by Wonder House Books | 25 April 2018",
    price: 57,
    img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Lose_Yourself.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "My First 1000 Words",
    author: "by Wonder House Books  | 1 January 2018",
    price: 149,
    img: "https://www.rollingstone.com/wp-content/uploads/2018/06/rs-146432-6b725a8c7cad1a0414c5a33f06299e9d2730ae2e.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "101 Panchatantra Stories for Children",
    author: "by Om Books Editorial Team | 30 September 2020",
    price: 135,
    img: "https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Pre-School Activities Pack ",
    author: "by Om Books Editorial Team  | 1 January 2021",
    price: 693,
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Relapse_Refill_Cover.jpg/220px-Relapse_Refill_Cover.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Early Learning Library Pack 1",
    author: "by Wonder House Books  | 6 December 2020",
    price: 289,
    img: "https://www.levelman.com/content/images/2023/05/81Ahe2x9qBL._UF1000-1000_QL80_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Blossom Moral Story Book for Kids ",
    author: "by Content Team at Target Publications",
    price: 80,
    img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Brain Activity Book for Kids",
    author: "by Maple Press | 1 September 2021",
    price: 86,
    img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Willy the Silly Panda",
    author: "by Rebecca Smith  | 14 December 2021",
    price: 120,
    img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Grandma's Bag of Stories",
    author: "by Sudha Murty | 1 January 2015",
    price: 157,
    img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
  },
];

export default list;
